'use strict';
const token = location.hash.slice(1) || sessionStorage.getItem('beamfix-token');
if (token) sessionStorage.setItem('beamfix-token', token);
history.replaceState(null, '', '/');
let state, busy = false, closed = false, selected = 'no_signal', connection = 'unknown', lastRender = '', poll;
const main = document.getElementById('main');
const titles = {no_signal:'No signal', black:'Black projection', desktop:'Desktop, no slides', room_monitors_only:'Room screens only'};
const captions = {no_signal:'The projector cannot find an input.', black:'The projector is on, but the image is dark.', desktop:'The desktop is visible; the presentation is missing.', room_monitors_only:'Room monitors work; the projector does not.'};
function el(tag, text, cls) { const e = document.createElement(tag); if(text !== undefined)e.textContent=text; if(cls)e.className=cls; return e; }
function append(parent, ...children) { children.forEach(c=>{if(c)parent.append(c);}); return parent; }
function button(label, handler, cls='') { const b=el('button',label,cls); b.type='button'; b.onclick=handler; return b; }
function error(message) { const box=document.getElementById('message'); box.textContent=message; box.hidden=false; }
async function api(path, body) {
 const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'X-BeamFix-Token':token||'',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});
 const data=await r.json(); if(!r.ok)throw new Error(data.error||'The local interface could not respond.'); return data;
}
async function act(action, extra={}) {
 if(busy)return; busy=true; document.getElementById('message').hidden=true;
 main.querySelectorAll('button').forEach(b=>b.disabled=true);
 try { state=await api('action',{action,revision:state.revision,...extra}); render(true); }
 catch(e){error(e.message); try{state=await api('state');render(true);}catch(_){} }
 finally {busy=false; main.querySelectorAll('button').forEach(b=>b.disabled=false);}
}
function heading(kicker,title,description){append(main,el('div',kicker,'eyebrow'),el('h1',title));if(description)main.append(el('p',description,'intro'));}
function flow(active){const f=el('nav',undefined,'flow');f.setAttribute('aria-label','Progress');['Describe','Identify','Try & verify'].forEach((x,i)=>f.append(el('span',`${i+1}  ${x}`,i===active?'active':'')));main.append(f);}
function connectionSelect(value, change) { const wrap=el('div');const label=el('label','How is the computer connected?');label.htmlFor='connection';const select=el('select');select.id='connection';Object.entries(state.connections).forEach(([k,v])=>{const o=el('option',v);o.value=k;select.append(o);});select.value=value;select.onchange=()=>change(select.value);return append(wrap,label,select); }
function home(){
 heading('Projector help, one step at a time','What do you see on the projector?','Choose the closest example. BeamFix will check the computer and guide you through what to try.');flow(0);
 const cards=el('div',undefined,'cards');Object.entries(titles).forEach(([key,label])=>{const b=button('',()=>{selected=key;render(true);},'card');b.setAttribute('aria-pressed',String(selected===key));const img=el('img');img.src='/'+key+'.svg';img.alt='Illustration: '+state.symptoms[key];append(b,img,el('strong',label),el('span',captions[key]));cards.append(b);});main.append(cards);
 const c=el('div',undefined,'connection');append(c,append(el('div'),el('h3','Start with the connection'),el('p','Your description helps tailor the checks. A classroom system can feed several screens from one computer output.')),connectionSelect(connection,v=>connection=v));main.append(c);
 const actions=el('div',undefined,'actions');append(actions,button('Start guided checks →',()=>act('start',{symptom:selected,connection}),'primary'),button('Read diagnostics only',()=>act('refresh')));main.append(actions);
 diagnostics();
}
function targets(){heading('Identify the output','Which output feeds the projector?','Compare these names with your Display settings. The connector name alone cannot identify a projector.');flow(1);const list=el('div',undefined,'stack narrow');state.outputs.forEach(o=>list.append(append(button('',()=>act('target',{target:o.name}),'target'),el('strong',o.name),el('small',o.description))));list.append(button('I am not sure / the projector is not listed',()=>act('target',{target:null})));main.append(list);main.append(el('p','For a classroom system, choose the computer output feeding the room. The projector may not appear separately.','notice narrow'));stopButton();}
function step(){heading(`Guided check ${state.session.attempts.length+1}`,state.step.title,state.step.reason);flow(2);const p=el('div',undefined,'panel narrow');append(p,el('span','MANUAL CHECK','badge'),el('p',state.step.instruction,'instruction'));append(p,append(el('div',undefined,'actions'),button('Done · check the result',()=>act('done'),'primary'),button('Skip this step',()=>act('skip'))));main.append(p);
 if(['activate','mode'].includes(state.step.code)){const a=el('div',undefined,'panel narrow');append(a,el('h3','Try with automatic undo'),el('p','BeamFix can check whether a protected attempt is available. You will see the exact proposed change before approving it.','muted'),button('Preview an automatic attempt',()=>act('preview')));main.append(a);}
 if(state.notice)main.append(el('p',state.notice,'notice narrow'));stopButton();diagnostics();}
function preview(){heading('Review before applying','Ready to try these settings?','Keep this page on another active screen. Leave cables and Display settings unchanged during the attempt.');const p=el('div',undefined,'panel narrow');const list=el('ol');state.preview.forEach(x=>list.append(el('li',x)));append(p,list,el('p','After each change, confirm the image on the projector itself within 15 seconds. No answer restores and stops. An image on room monitors alone is not confirmation.','notice'));append(p,append(el('div',undefined,'actions'),button('Try with automatic undo',()=>act('apply'),'primary'),button('Use manual instructions',()=>act('manual'))));main.append(p);stopButton();}
function observe(){heading('Look at the projector itself','What do you see now?','The computer reading cannot confirm whether the projected image is correct.');let path=state.session.connection_path;if(state.step.code==='direct'){main.append(connectionSelect(path,v=>path=v));}const list=el('div',undefined,'stack narrow');const options={resolved:'The projector itself shows the image I wanted',...state.symptoms,unverified:'I cannot verify the image'};Object.entries(options).forEach(([k,v])=>list.append(button(v,()=>act('observe',{observation:k,connection:path}),k==='resolved'?'primary':'')));main.append(list);stopButton();diagnostics();}
function running(){heading('Protected attempt','Checking settings or restoring…','Keep this page open. BeamFix will ask you to verify the projected image when the change has been checked.');main.append(append(el('div',undefined,'panel narrow'),el('span',undefined,'spinner'),el('span','Waiting for the recovery worker. This can take a little while.')));main.append(button('Stop and request restore',()=>act('stop')));}
function confirm(){const c=state.confirmation;heading(`Trial ${c.index} of ${c.total}`,'Does the projector show the expected image?','Confirm only if the projector itself displays the image you wanted.');const p=el('div',undefined,'panel narrow');const timer=el('div',String(Math.ceil(c.seconds))+' s','timer');timer.id='timer';append(p,timer,el('p',c.description),el('p','No answer restores the original settings and stops.','muted'));const actions=el('div',undefined,'actions');const decide=d=>act('decision',{nonce:c.nonce,decision:d});append(actions,button('Yes · keep this image',()=>decide('keep'),'primary'));if(c.modes)actions.append(button('No · restore, then try next',()=>decide('next')));actions.append(button('Stop and restore',()=>decide('undo')));append(p,actions);main.append(p);}
function summary(){const ok=state.session.outcome==='resolved';heading('Session summary',ok?'Image confirmed by you':'The image is not confirmed',ok?'You reported seeing the expected image on the projector.':'Completed and skipped checks do not establish the cause of the problem.');if(state.result)main.append(el('pre',state.result.detail,ok?'success':'notice'));else main.append(el('p',({interrupted:'You stopped the guided checks.',insufficient:'More information or visual verification is needed.',unresolved:'No more guided steps are available for this session.'})[state.session.outcome]||'The visual result is recorded below.',ok?'success':'notice'));
 const p=el('div',undefined,'panel narrow');append(p,el('h3','Checks in this session'),el('p','Initial symptom: '+(state.symptoms[state.session.initial_symptom]||'Not provided'),'muted'),el('p','Initial connection: '+(state.connections[state.session.initial_connection]||'Not provided'),'muted'),el('p','Latest connection: '+state.connections[state.session.connection_path],'muted'));
 if(!state.session.attempts.length)p.append(el('p','No steps performed.'));
 state.session.attempts.forEach(a=>{const row=el('div',undefined,'history');append(row,el('h3',a.step.title),el('span',a.automatic_result?'AUTOMATIC ATTEMPT':a.performed?'PERFORMED':'SKIPPED · UNVERIFIED','badge'));if(a.performed)append(row,el('p','Before: '+a.before),a.after?el('p','After: '+a.after):el('p','No new diagnostic reading was collected after the automatic attempt.'),el('p','Visual result: '+(a.observation||'not confirmed')));if(a.automatic_result)row.append(el('p',a.automatic_result));p.append(row);});main.append(p);append(main,append(el('div',undefined,'actions'),button('Start again',()=>act('home'),'primary'),button('Save session report',()=>download({schema_version:1,beamfix_version:state.version,demo:state.demo,session:state.session,automatic_result:state.result},'beamfix-session.json')),button('Read diagnostics again',()=>act('refresh'))));diagnostics();}
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function diagnostics(){if(!state.report)return;const r=state.report;const d=el('details',undefined,'panel');d.open=state.phase==='home';append(d,el('summary','Computer diagnostics · '+({0:'no issues detected',1:'warnings reported',2:'incomplete observations'})[r.exit_code]));append(d,el('p',`${r.snapshot.desktop} · ${r.snapshot.session} · ${r.snapshot.system} ${r.snapshot.kernel}`,'muted'),el('p','Detection and reported modes do not prove a visible image. Readings below describe the last collection.','muted'));
 const grid=el('div',undefined,'report-grid');r.snapshot.connectors.forEach(c=>{const p=el('div',undefined,'report-card');append(p,el('h3',c.name),el('p',`${c.kind} · ${c.status} · ${c.enabled}`));const cm=c.current_mode;append(p,el('p',cm?.mode?`${cm.mode.width} × ${cm.mode.height} @ ${cm.mode.refresh_hz.toFixed(2)} Hz · ${cm.state}`:'Current mode: '+(cm?.state||'unverified')),el('p',cm?.reason||'Current mode was not observed.','muted'));if(c.signal){p.append(el('p','Signal: '+c.signal.state+' · '+c.signal.reason));const detail=el('details');append(detail,el('summary','Signal properties and timing'),el('pre',JSON.stringify(c.signal,null,2)));p.append(detail);}grid.append(p);});d.append(grid);r.findings.forEach(f=>append(d,append(el('div',undefined,'finding'),el('strong',f.severity.toUpperCase()+' · '+f.message),el('span',f.suggestion))));r.snapshot.errors.forEach(e=>d.append(el('p',e,'notice')));d.append(button('Save diagnostic JSON',()=>download({...r,...(state.demo?{demo:true}:{})},'beamfix-doctor.json')));main.append(d);}
function stopButton(){main.append(append(el('div',undefined,'actions'),button('End checks and show summary',()=>act('stop'),'quiet')));}
function render(force=false){
 document.getElementById('version').textContent='v'+state.version;document.getElementById('demo').hidden=!state.demo;
 const key=state.phase+':'+state.revision;
 if(!force&&lastRender===key){const timer=document.getElementById('timer');if(timer&&state.confirmation)timer.textContent=Math.ceil(state.confirmation.seconds)+' s';return;}
 const phaseChanged=lastRender.split(':')[0]!==state.phase;lastRender=key;main.replaceChildren();
 ({home,target:targets,step,preview,observe,running,confirm,summary}[state.phase]||home)();
 if(phaseChanged){main.focus({preventScroll:true});window.scrollTo(0,0);}
}
document.getElementById('brand').onclick=e=>{e.preventDefault();if(state&&['home','summary'].includes(state.phase))act('home');};
document.getElementById('quit').onclick=async()=>{try{await api('quit',{});closed=true;clearTimeout(poll);headingClosed();}catch(e){error(e.message);}};
function headingClosed(){main.replaceChildren();heading('BeamFix closed','You can close this tab.','If a display attempt was active, the independent worker will attempt recovery. Use Display settings if the image does not return.');document.getElementById('quit').disabled=true;}
async function tick(){if(closed)return;try{if(!busy){const next=await api('state');if(closed)return;if(!state||next.revision>=state.revision){state=next;render();}}poll=setTimeout(tick,500);}catch(e){if(closed)return;error('Connection to BeamFix lost. Unconfirmed automatic changes request recovery; check Display settings if needed. '+e.message);poll=setTimeout(tick,2000);}}
window.addEventListener('pagehide',()=>{if(state&&['running','confirm'].includes(state.phase))fetch('/api/action',{method:'POST',headers:{'X-BeamFix-Token':token,'Content-Type':'application/json'},body:JSON.stringify({action:'stop',revision:state.revision}),keepalive:true}).catch(()=>{});});
tick();
